# Generated by Django 5.2.12 on 2026-04-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Apellido y nombres del autor', max_length=30)),
                ('nacionalidad', models.CharField(blank=True, help_text='Nacionalidad del autor', max_length=30, null=True)),
                ('fecNacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del autor', null=True)),
                ('fecDefuncion', models.DateField(blank=True, help_text='Fecha de defunción del autor', null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios referidos al autor', null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
