# Generated by Django 5.2.12 on 2026-09-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Apellido y nombres del autor', max_length=30, verbose_name='Apellido y Nombres')),
                ('nacionalidad', models.CharField(blank=True, help_text='Nacionalidad del autor', max_length=30, null=True)),
                ('fecNacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del autor', null=True)),
                ('fecDefuncion', models.DateField(blank=True, help_text='Fecha de defunción del autor', null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios referidos al autor', null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del libro', max_length=40, verbose_name='Apellido y Nombres')),
                ('editorial', models.CharField(blank=True, help_text='Editorial del libro', max_length=30, null=True)),
                ('anioPub', models.IntegerField(blank=True, help_text='Año de publicación', null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios referidos al libro', null=True)),
                ('autor', models.ManyToManyField(to='apBiblioteca.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
