# Generated by Django 5.2.12 on 2026-04-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(default='', help_text='Apellido y nombres del autor', max_length=30),
            preserve_default=False,
        ),
    ]
