# Generated by Django 5.2.12 on 2026-04-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apBiblioteca', '0002_autor_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='apellido',
        ),
    ]
