# Generated by Django 5.2.12 on 2026-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apBiblioteca', '0003_remove_autor_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='activo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(help_text='Apellido y nombres del autor', max_length=30, verbose_name='Apellido y Nombres'),
        ),
    ]
