# Generated by Django 5.2.12 on 2026-08-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apBiblioteca', '0004_autor_activo_alter_autor_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del libro', max_length=30, verbose_name='Apellido y Nombres')),
                ('editorial', models.CharField(blank=True, help_text='Editorial del libro', max_length=30, null=True)),
                ('anioPub', models.IntegerField(blank=True, help_text='Año de publicación', null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios referidos al libro', null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apBiblioteca.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
