# Generated by Django 5.2.12 on 2026-08-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apBiblioteca', '0005_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(help_text='Apellido y nombres del autor', max_length=40, verbose_name='Apellido y Nombres'),
        ),
    ]
